paths:
  root: "/Volumes/Music/Prince"
  category_roots:
    official: "Official"
    unofficial: "Unofficial"
    live: "Live"
    outtakes: "Outtakes"
  logs: null
  pv_sqlite: "princevault.db"
  pv_xml_dir: "~/data/princevault/xml"

behavior:
  tag_only: false
  copy_files: true
  move_files: false
  write_tags: true
  ask_confirmation: true
  llm_always: true
  min_auto_score: null

naming:
  rules_file: "config/naming_rules.md"
  rules_format: "text"
  templates_default:
    live: "{date} - {city} - {venue} - {tracknum} {title} [{source}]{lineage_short}"
    outtake: "{era}/{session_date} - {title}"
    official: "{album}/{tracknum} {title}"
    unofficial: "{setname}/{tracknum} {title}"

fields:
  keep_custom_tags:
    - "LINEAGE"
    - "TAPER"
    - "TRANSFER"
  prefer_dates_from:
    - "PrinceVault"
    - "MusicBrainz" 
    - "FileTags"

api:
  acoustid_key: "env:ACOUSTID_KEY"
  musicbrainz_user_agent: "PrinceTagger/0.1 (kverde@gmail.com)"

llm:
  provider: "openrouter"
  model: "google/gemini-2.5-flash"
  temperature: 0.2
  max_tokens: 800
  approval_required: true
  system_prompt: "You are a Prince music metadata expert. Analyze the provided data sources (AcoustID, MusicBrainz, PrinceVault) and return normalized metadata in strict JSON format. 

DATA SOURCE PRIORITY:
1. MusicBrainz data is the MOST RELIABLE and should be prioritized for core metadata (title, artist, album, date, track numbers)
2. PrinceVault data is valuable for Prince-specific context BUT can sometimes incorrectly match official songs to bootleg/live versions - use cautiously for categorization
3. AcoustID provides fingerprint matches but may have inconsistent metadata quality

DECISION RULES:
- If MusicBrainz shows an official release, trust that over PrinceVault categorization
- Only use PrinceVault's 'live' or 'bootleg' categorization if MusicBrainz doesn't show official releases
- For recording dates and venues, prefer PrinceVault only when MusicBrainz lacks this detail
- Be especially careful when PrinceVault suggests a well-known studio song is 'live' - verify against MusicBrainz releases

Categories: official (commercial releases), live (concerts), outtakes (studio outtakes/demos), unofficial (bootleg compilations). Never invent information not supported by the sources."
  
  user_prompt_template: |
    Normalize metadata for audio file: {filename}
    Duration: {duration} seconds
    Format: {format}
    Bitrate: {bitrate}
    
    CURRENT FILE TAGS:
    {current_tags}
    
    AVAILABLE DATA SOURCES:
    {acoustid_data}
    {musicbrainz_data}
    {princevault_data}
    
    Please return normalized metadata in JSON format with these fields:
    {{
      "title": "song title",
      "artist": "artist name", 
      "album": "album name or null",
      "track_number": number or null,
      "year": 4-digit year or null,
      "date": "YYYY-MM-DD or YYYY or null",
      "category": "official/live/outtakes/unofficial",
      "recording_date": "YYYY-MM-DD or descriptive date",
      "venue": "recording location or null",
      "session_info": "session details or null",
      "genre": "music genre or null",
      "comments": "additional context or null",
      "confidence": 0.0-1.0 score
    }}
    
    Return ONLY valid JSON, no other text.